name: .NET CI

on:
  push:
    branches: [ "main", "master", "testy-jednostkowe" ]
  pull_request:
    branches: [ "main", "master", "testy-jednostkowe" ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore DevOps-projekt-zaliczeniowy/DevOps-projekt-zaliczeniowy.csproj

    - name: Build
      run: dotnet build DevOps-projekt-zaliczeniowy/DevOps-projekt-zaliczeniowy.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test DevOps-projekt-zaliczeniowy.Tests/DevOps-projekt-zaliczeniowy.Tests.csproj --no-build --configuration Release --verbosity normal
